language: node_js
services:
- docker
install:
- docker build -t rabbitmq ./images/RabbitMQ
- docker run -d --rm --env-file ./bin/.env -p 5779:5672 -p 15779:15672 --name rabbit-lib-test
  rabbitmq
- sleep 5
before_script:
- npm install -g npm@'>=2.13.5'
- npm i
script:
- npm run test
deploy:
  provider: npm
  email:
    secure: uRY50P14XsmgeE0gW+C1xfGGvMVsk3cPk8jhBEF/xJwzs+yLMJu5t7CY1PhVdQSo3BoiApz8uYnKoQXfYBZ87TEju27jAE2KTafguFSHEjQnunWfeSxZQ5NgOAT7OWWYTTOrvcD5hlZOSnqLXVB3RIkkZZJrK6p+R6SYud9r3/eY3lJVDdSj/mnsd6C7CGmM/vammi3U6IZY1J3v7Nn9Rke4lsDFNfvCPPfycsttuZ20aR2PdtEwOqLwW5v17L3+06x1lDezcplV/yraoNZDoRJ6P4OW2wRhIzzH5cymWvN6TBfBHkIriDwBYexce7PUXIA7SnWhLQ62fzonn0Q/vBJd1wRWDMauAooWjGP1lMwEI1SGx9ZjEJ9QA1T3k0LBtnQDYHUnELPQoNWQoVA1brpCmyXV5MMRCRbViEbWb6Q4ykzr2dbM25f6tkRpyNwOfTEN7O53PYz5zjJG9+HTG+WX4MEeYAtzl1BHNs9vpbdYVoQmcZ34MrADul986GI1ZCuOtcyMlU2CtPPc0o75eev7i7uROU8aYH042MRdxwpezxFVGSVqg3CISVK0BUtahs7c7kXPYAq/g+SyMYw4SRvyQBrVFRNKWtGTyApSWwVpet08BJHey2bHtlii2BAK2k4DlPRwuTYJSWUpNvKeh/WtWgwotPDcrZvBoY8IxHM=
  skip_cleanup: true
  api_key:
    secure: IRDrOAcnjnI8OffwCO77Vgg3I7kvWAMPEAqKCX2kpPGDd+yIggxS+EaS6upsBALLlZDpOeDIhdE5rhFx0IxvKKUCWoccFV4cfrS2HqOtXjBvn0OZTfRgvqDhoKOxpdnIIXHqcIubRSt6896/gSEIvLa6YnHnZBRXhgXG3ngIGHiHydD1X0dg3MR1C+J41R6hpFmeBPSZjT10xbHJ+33a264TG6j8qxQ1M2STp9WDjLFOO/uwzX+DUjKTqBiHBU0XQKhriguxW+p7/gQAnyXKolqekWPsOUrjxcEk2wOh0L8KzVUAPrI4T8QXR7EFEV4T/Nkhex2GnJ+dp1tw5AjgBQwA/05VGtWXo9XVh/o0RsYhEiZv9ZHOi80UlkKme9ySr6fwn4HWd1hPvTiygPOGpwtcDhkNF0dldzBbVwAIlFIAJA7Tq0YdhOmw4YLr06AZTuS311H74hOMT2ZCswmtPxEG+HXwdxVvF6eZoX1Sy1PUYaW7ptz8opDLIu6kTQpdweaWf11rcQXCDWGyXuM25hhBbbcsT+staP3BLjPhSVgxb2NBVAvZ+8cSBV2/KmMy2aE6MLcfNRnjFa3UoRe3RoG5IyxftJVdHKCJh/KeKF3AnpS5Rwh0BcZcxIxCxnSdfyLLNo/oR3WJrxoaGWjDzYWM+t9wLpd0xg1czHu2t+k=
  on:
    tags: true
    repo: webnator/maestro-rabbit
