language: node_js
services:
- docker
install:
- docker build -t rabbitmq ./images/RabbitMQ
- docker run -d --rm --env-file ./bin/.env -p 5779:5672 -p 15779:15672 --name rabbit-lib-test
  rabbitmq
- sleep 5
before_script:
- npm install -g npm@'>=2.13.5'
- npm i
script:
- npm run test
deploy:
  provider: npm
  email:
    secure: ea9AIRPS4t8MVRo8ZXrbuDD7b8eLHkiW1V4VVhbVVQzO5teP6+76zrXQ36SqGjrtFNyCE9Gd+p9hwMQLMX+CSykvtLhF53Za6MhpFgImnG6y3/1a5EqqbJ18V6057yN7iZHvMKV11Aov4FRmivx76wTiMsBzVhVZKn5T7O799RUxopHZ2mk3RfBo9QvnjuNjVfUJc/vsPfX8/Qd3BnvZrYP5d1ncRwJwhjoZTHwFEV+3J7JmPmhTqzFdA1m8aQIMQ4S0mHLnSpSjslxxjFcOwm8W1+GQlBtc2ga1wRNMa/PchxNFPo/CTWiP5Rv192nNw68BlGSBC01alWXrS3A6RO/JUEU2q5qF7dd5qvE/gjE8jqj6TDEfIAEKAyew2q383T6QoVBDKH7oCaL3xYMjj6ie7JbWsWT+rqGURced0d9nRgUErYLI6RGO2odYu2PUw27TkzA0ewz84YBscWvAukexxrRlOiP9IwIeg0cekr/hrYQOYiWFhHPXWFxjWhUvt+E84x+Ijdo9RaVSmVvY7UiLDQFewOCkWhDz6vTMjWxjoCX3QDIbzzah6WjFlhtyMbx8EZYolKDCuud2iou40HNvuGn4j3b6epcdowFtO2BAXolMuqSsyz9gRjwKxFiPpfF7VztTPNONOfWr8kn8I3zNu28CoM4K26PVmILFx9E=
  api_key:
    secure: LYLybvs4btFvEZqqsba3BFR/tAkN1Loh3YTlB4OLgAdabMGIoR2komCWXD3UR3jUG5XclDVanvypG60LgiaB0Vb8Btd8Q6matk7slr/MLDYKX3MLguYwT42yqgj1uiO244bEqEcM2KBTW8TBjNlkchgwWLX+R45Qgg9B0M6RjfHnNFia4SlCYFiwQnehzOQMEcmlFwobh6Zc2Nua1cV6GAZtwPK2O1WaE9+fX9pmQPnbDV5NUWh0AbU9t1RTTwsHHbR2kegmaVPRiEjiivxYQoPzT9ZXBFWcwaQNMIejxeZCIzFgvgVwLLz/x9mmCbSeZZhv4C1ro/jcMGeP2BpZJSXh8eY5XUvp9CZcu7204sY+nnU8iRG7BVf2L/fTi7KFikaOdUb6Khfaiz5+DFLukw/ptlAabSHyGoOoJDMFs3oMxcf7n1nE8IfN3LRCWEUK1YOlrs3FzFoAuQd8hacNT70Yu9YiHhzuSCfLVCAyO9i0BWrTPPpTIPnFcYXV3+ZIXRQoNVjFev8+9psglcCToGVy++zZ827vuY8IWBKpZQKivsj5toV5k3vb0ONgobBLptQm0kAxbm1Gqd4zuTl9Ff7kIpaTKPcUJI3+WT6rYymc10ytW8vbqRcUwoIJje34tiYU5L1395Gxy8vpXUfopmBM6CJYLa1u2XLBSCP6YVM=
  skip_cleanup: true
  on:
    tags: true
    repo: webnator/maestro-rabbit
