language: node_js
services:
- docker
install:
- docker build -t rabbitmq ./images/RabbitMQ
- docker run -d --rm --env-file ./bin/.env -p 5779:5672 -p 15779:15672 --name rabbit-lib-test
  rabbitmq
- sleep 5
before_script:
- npm install -g npm@'>=2.13.5'
- npm i
script:
- npm run test
deploy:
  provider: npm
  email: webnator@gmail.com
  api_key:
    secure: pLOMzqc8zPl1Mx3x5C/vRlFAqtdu/MZyBCNlUerkc0QOW6+VTM4IcmGUJAu5pYDzYMrbz3D0ud8J2+egYEZceQ4hZWw3WuEGDh3PMwkXmvLfnZAXPpcUJe/50pvMOdh7tMRSxHSme9PqJFFd8H5JV1f+oOmkv0wbsjvQu5yxRyG+1qbG7X7JDRUYz/DLe3OkuriG4T3+5yXKu/tPwI90mQ/qY/9Twk0bv+yip99t2nOs8nd9gCKe8H8o4KGFwk3XXyHNsZSIEw5653XUUMcLZqCEbHB9qFELfXhM4jnju6kMXW+3SgGCIQ/hlLWEBI5CysSlEb+EJJXi++QVBqpvtZWx5uPLzfIozf/eTGypp4Y7Vlx/WBEk1OTTEbcnKkT3CdL6AwBFB+Y1ggi9kq8L/XkpOmPa9ZiH+Egj9JAUYEviZpiIloF6eeEO8dXiMaP/zETW+J3vYGNVvM0bNvoCx4l9C6efr9voy/BEJTTZOWplp7L7GfHO1eGUPfYJwODblULhrl24Rm4ppe6N46iuICgVNV45bx6RsiAZdPmCQMbj0h3f5+Ix0y+bQsz1bNyRTCn6ndEq3heR80iTlugrEmDC2BePOQdWSrWupTLwonxocRKADVmApOLbqTxZgOb6kWfZQ3qwT4w/NG81xqNuo9Zlk0PxQC7fKUSbpTw++Gg=
  on:
    tags: true
    repo: webnator/maestro-rabbit
